version: 2

version: 0.2

env:
  shell: bash
  git-credential-helper: yes

phases:
  install:
    runtime-versions:
      nodejs: 12
      python: 3.7
    commands:
      - curl -Ls https://mapbox-release-engineering.s3.amazonaws.com/mbx-ci/latest/mbx-ci-linux-amd64 > mbx-ci && chmod 755 ./mbx-ci
      - echo "CURRENT DIRECTORY..." && /bin/bash -c pwd
      - "chmod +x ./.githooks/*"
      - echo "//registry.npmjs.org/:_authToken=$NPMAccessToken" > ./.npmrc
      - git config --global url."https://".insteadOf git://
      - npm install

  build:
    machine: true
    parallelism: 1
    steps:
      - run:
          name: "Install Yarn PPAs"
          command: "curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - && echo 'deb https://dl.yarnpkg.com/debian/ stable main' | sudo tee /etc/apt/sources.list.d/yarn.list"
      - run:
          name: "Update APT Cache & Install latest yarn"
          command: "sudo apt-get -y update && sudo apt-get install -y yarn curl"
      - run:
          name: "Auth NPM"
          command: "echo \"//registry.npmjs.org/:_authToken=$NPMAccessToken\" > ~/.npmrc"
      - run:
          name: "Locked NPM Version"
          command: "source ~/.bashrc && nvm install 8.11.3 && nvm use --delete-prefix v6.1.0 --silent && nvm use 8.11.3 && nvm alias default 8.11.3"
      - run:
          name: "Install Rust"
          command: "curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain 1.34.0"
      - run:
          name: "Install Clippy"
          command: "~/.cargo/bin/rustup component add clippy"

      - checkout

      - run:
          name: "yarn install"
          command: "source ~/.bashrc && yarn install"
      - run:
          name: "yarn test"
          command: "source ~/.bashrc && yarn test"
      - run:
          name: "cargo test"
          command: "~/.cargo/bin/cargo test"
      - run:
          name: "cargo clippy"
          command: "~/.cargo/bin/cargo clippy --all-targets --all-features -- -D warnings"
